### ISSUE TITLE
‘Flag as Inappropriate’ button is inactive 

### ISSUE THREAD

**Issue by SandyHsiao** [info442-sp21/d-team#93]
Severity: minor
Description: The 'Flag as Inappropriate' button does not provide any indication of whether it's being selected/flagged or not
Reproduce: enter the website, click 'view details', click 'Flag as appropriate'
Environment: Mac OS Catalina, Chrome browser

**Comment by ashshah1** [comment]
Based off of our initial design spec, this is not something we planned on incorporating, which is outlined here: https://github.com/info442-sp21/d-team/issues/68. However, we do agree that it is not great user experience but cannot fix it in the given time frame.

**Comment by cherimarie** [comment]
Showing UI that isn't tied to any functionality is poor user experience. I think this issue ought to be kept open, even if it can't be fixed in this sprint. A potential fix would be removing the button entirely, if wiring it up to save data ("flagged" attribute on post) in the database isn't possible.
